#prettier-ignore
openapi: 3.0.0
info:
  title: Courses API
  version: 1.0.0
  description: API для получения списка курсов

paths:
  /v1/courses/chosen:
    get:
      summary: Получить список курсов
      description: Возвращает список курсов с поддержкой пагинации и фильтрации по статусу.
      tags:
        - Courses
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
          description: Ограничение на количество возвращаемых курсов.
        - name: offset
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
          description: Количество записей для пропуска (для пагинации).
        - name: status
          in: query
          required: true
          schema:
            type: string
            enum: [active, completed]
          description: Статус курсов, которые нужно получить (active или completed).
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации в формате Bearer.

      responses:
        '200':
          description: Успешный ответ со списком курсов
          content:
            application/json:
              schema:
                type: object
                properties:
                  info:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: Общее количество курсов, подходящих под запрос
                      courses:
                        type: array
                        description: Список курсов
                        items:
                          type: object
                          properties:
                            creator:
                              type: string
                              description: Фамилия и имя создателя курса
                            photo:
                              type: string
                              description: Название фото курса в формате JPG
                            title:
                              type: string
                              description: Название курса
                            duration:
                              type: integer
                              description: Продолжительность курса (в часах)

        '400':
          description: Ошибка в параметрах запроса
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Неверные значения limit или offset или status'

          '403':
            description: Токен авторизации невалиден
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: ''
        

        '404':
          description: Курсы не найдены
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'У этого пользователя нет выбранных курсов со статусом ${status}'

        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Внутренняя ошибка сервера'
