#prettier-ignore
openapi: 3.0.0
info:
  title: lessons API
  version: 1.0.0
  description: API для получения списка уроков


paths:
  /v1/lessons/new:
    post:
      summary: Создать урок
      tags:
        - Lessons
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации в формате Bearer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - sectionId
                - courseId
                - info
              properties:
                name:
                  type: string
                  description: Название урока
                sectionId:
                  type: integer
                  description: ID секции
                courseId:
                  type: integer
                  description: ID курса
                info:
                  type: object
                  description: Содержимое урока
                  properties:
                    title:
                      type: string
                      description: Заголовок урока
                      example: "Заголовок урока"
                    content:
                      type: string
                      description: Содержимое урока
                      example: "Содержимое урока"
                    url:
                      type: array
                      items:
                        type: string
                      description: Ссылки на видео
                      example: ["https://www.youtube.com/watch?v=123", "https://www.youtube.com/watch?v=456"]
      responses:
        '201':
          description: Успешное создание урока
          content:
            application/json:
              schema:
                type: object
                properties:
                  lessonId:
                    type: integer
                  sectionId:
                    type: integer
                  courseId:
                    type: integer
                  info:
                    type: object
                    description: Содержимое урока
                    properties:
                      title:
                        type: string
                        description: Заголовок урока
                        example: "Заголовок урока"
                      content:
                        type: string
                        description: Содержимое урока
                        example: "Содержимое урока"
                      url:
                        type: array
                        items:
                          type: string
                        description: Ссылки на видео
                        example: ["https://www.youtube.com/watch?v=123", "https://www.youtube.com/watch?v=456"]
        "400":  
          description: Не все поля заполнены
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Не все поля заполнены"
        "403":  
          description: Нет достпупа к данным
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 403
                  message:
                    type: string
                    example: "У вас недостаточно прав для редактирования этого курса"
        '404':
          description: Раздела с таким id не существует
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "Раздела с таким id не существует"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string       

  /v1/lessons/end:
    post:
      summary: Завершить урок
      tags:
        - Lessons
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации в формате Bearer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: Id урока
                  example: 2
      responses:
        '201':
          description: Урок успешно завершен
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: integer
                    example: Урок успешно завершен

        "400":  
          description: Не все поля заполнены
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Не все поля заполнены"

        "403":
            description: Недействительный токен
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: integer
                      example: 40102
                    message:
                      type: string
                      example: "Недействительный токен"

        "406":  
          description: Пользователь не подписан на данный курс
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 406
                  message:
                    type: string
                    example: "Пользователь не подписан на данный курс"
        "409":  
          description: Пользователь уже завершил этот урок 
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 409
                  message:
                    type: string
                    example: "Урок уже завершен"

        "423":  
          description: Завершите предыдущую секцию для просмотра содержимого следующей
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 423
                  message:
                    type: string
                    example: "Завершите предыдущую секцию для просмотра содержимого следующей"

        '500':  
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string       

  /v1/lessons/list/{id}:
    get:
      summary: Получить список всех уроков и тестов в секции
      tags:
        - Lessons
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации в формате Bearer.
      responses:
        "200":
          description: Список уроков
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "урок 1"
                    isCompleted:
                      type: boolean
                      example: false
                      description: Является ли урок завершенным
        "400":  
          description: Не все поля заполнены
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Не все поля заполнены"
        '403':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 40102
                  message:
                    type: string
                    example: 'Недействительный токен'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string      

  /v1/lessons/info/{id}:
    get:
      summary: Получить информацию о конкретном уроке
      tags:
        - Lessons
    
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации в формате Bearer.
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Успешное создание урока
          content:
            application/json:
              schema:
                type: object
                properties:
                  lessonId:
                    type: integer
                  sectionId:
                    type: integer
                  courseId:
                    type: integer
                  isCompleted:
                    type: boolean
                    example: false
                  info:
                    type: object
                    description: Содержимое урока
                    properties:
                      title:
                        type: string
                        description: Заголовок урока
                        example: "Заголовок урока"
                      content:
                        type: string
                        description: Содержимое урока
                        example: "Содержимое урока"
                      url:
                        type: array
                        items:
                          type: string
                        description: Ссылки на видео
                        example: ["https://www.youtube.com/watch?v=123", "https://www.youtube.com/watch?v=456"]
        "400":  
          description: Не все поля заполнены
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Не все поля заполнены"
        '403':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 40102
                  message:
                    type: string
                    example: 'Недействительный токен'
        "423":  
          description: Завершите предыдущую секцию для просмотра содержимого следующей
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 423
                  message:
                    type: string
                    example: "Завершите предыдущую секцию для просмотра содержимого следующей"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string     
  /v1/lessons/redact:
    put:
      summary: Обновить урок
      tags:
        - Lessons
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации в формате Bearer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - lessonId
                - name
                - sectionId
                - courseId
                - info
              properties:
                lessonId:
                  type: integer
                  description: ID урока
                name:
                  type: string
                  description: Название урока
                sectionId:
                  type: integer
                  description: ID секции
                courseId:
                  type: integer
                  description: ID курса
                info:
                  type: object
                  description: Содержимое урока
                  properties:
                    title:
                      type: string
                      description: Заголовок урока
                      example: "Заголовок урока"
                    content:
                      type: string
                      description: Содержимое урока
                      example: "Содержимое урока"
                    url:
                      type: array
                      items:
                        type: string
                      description: Ссылки на видео
                      example: ["https://www.youtube.com/watch?v=123", "https://www.youtube.com/watch?v=456"]
      responses:
        '200':
          description: Успешное редактированние урока
          content:
            application/json:
              schema:
                type: object
                properties:
                  lessonId:
                    type: integer
                  sectionId:
                    type: integer
                  courseId:
                    type: integer
                  info:
                    type: object
                    description: Содержимое урока
                    properties:
                      title:
                        type: string
                        description: Заголовок урока
                        example: "Заголовок урока"
                      content:
                        type: string
                        description: Содержимое урока
                        example: "Содержимое урока"
                      url:
                        type: array
                        items:
                          type: string
                        description: Ссылки на видео
                        example: ["https://www.youtube.com/watch?v=123", "https://www.youtube.com/watch?v=456"]
        "400":  
          description: Не все поля заполнены
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Не все поля заполнены"
        "403":  
          description: Нет достпупа к данным
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 403
                  message:
                    type: string
                    example: "У вас недостаточно прав для редактирования этого курса"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string       
  /v1/lessons:
    delete:
      summary: Удалить урок
      tags:
        - Lessons
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации в формате Bearer.
        - name: lessonId
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: sectionId
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: courseId
          in: query
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Успешное удаление урока
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Урок успешно удален"

        "400":  
          description: Не все поля заполнены
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Не все поля заполнены"
        "403":  
          description: Нет достпупа к данным
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 403
                  message:
                    type: string
                    example: "У вас недостаточно прав для редактирования этого курса"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string
