#prettier-ignore
openapi: 3.0.0
info:
  title: API Photo
  version: 1.0.0
  description: Getting Photo

paths:
  /v1/profiles/avatars/all:
    get:
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: string
            example: "Bearer your_token_here"
      summary: Получить все аватары пользователей
      description: Возвращает все изображения аватаров пользователей с сервера.
      tags:
        - Photos
      responses:
        '200':
          description: Успешное получение всех изображений аватаров пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "cristalAvatar.jpg"
        '403':
          description: Неавторизованный пользователь
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 40102
                  message:
                    type: string
                    example: "Недействительный токен"

  /v1/profiles/avatars/url/{filename}:
    get:
      summary: Получить аватар пользователя по имени файла
      description: Возвращает запрашиваемое изображение аватара пользователя с сервера.
      tags:
        - Photos
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer your_token_here"
        - name: filename
          in: path
          required: true
          description: Название файла изображения аватара
          schema:
            type: string
      responses:
        '200':
          description: Успешное получение изображения аватара
          content:
            image/*:
              schema:
                type: string
                format: binary
        '403':
          description: Неавторизованный пользователь
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 40102
                  message:
                    type: string
                    example: "Недействительный токен"


  /v1/courses/photo/url/{filename}:
    get:
      summary: Получить обложку курса по имени файла
      description: Возвращает запрашиваемое изображение обложки курса с сервера.
      tags:
        - Photos
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer your_token_here"
        - name: filename
          in: path
          required: true
          description: Название файла изображения обложки курса
          schema:
            type: string
      responses:
        '200':
          description: Успешное получение изображения аватара
          content:
            image/*:
              schema:
                type: string
                format: binary
        '403':
          description: Неавторизованный пользователь
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 40102
                  message:
                    type: string
                    example: "Недействительный токен"
