#prettier-ignore
openapi: 3.0.0
info:
  title: API Photo
  version: 1.0.0
  description: Getting Photo

paths:
  /profiles/avatars/url/{filename}:
    get:
      summary: Получить аватар пользователя по имени файла
      description: Возвращает запрашиваемое изображение аватара пользователя с сервера.
      tags:
        - Photos
      parameters:
        - name: filename
          in: path
          required: true
          description: Название файла изображения аватара
          schema:
            type: string
      responses:
        '200':
          description: Успешное получение изображения аватара
          content:
            image/*:
              schema:
                type: string
                format: binary


  /courses/photo/url/{filename}:
    get:
      summary: Получить обложку курса по имени файла
      description: Возвращает запрашиваемое изображение обложки курса с сервера.
      tags:
        - Photos
      parameters:
        - name: filename
          in: path
          required: true
          description: Название файла изображения обложки курса
          schema:
            type: string
      responses:
        '200':
          description: Успешное получение изображения аватара
          content:
            image/*:
              schema:
                type: string
                format: binary
